version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- sh -c "npm install && node index.js"
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true 
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile.prod
    image: lelunaa/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - db
      - app

  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge  